
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testArithmetic.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testBitPatterns.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testBox.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testBoxAlgo.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testClassification.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testColor.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testError.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testExtractEuler.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testExtractSHRT.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testFrustum.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testFrustumTest.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testFun.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testFunction.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testInterop.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testInterval.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testInvert.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testJacobiEigenSolver.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testLimits.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testLineAlgo.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testMatrix.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testMiscMatrixAlgo.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testProcrustes.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testQuat.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testQuatSetRotation.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testQuatSlerp.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testRandom.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testRoots.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testShear.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testSize.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testTinySVD.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testToFloat.cpp"
#include "../../thirdparty/owemdjee/Imath/src/ImathTest/testVec.cpp"

#include "../../thirdparty/owemdjee/Imath/src/ImathTest/main.cpp"

