
directories:
	../../thirdparty/owemdjee/quadsort/src/extra/

	# ../../thirdparty/owemdjee/quadsort/src/bench.c

	# ../../thirdparty/owemdjee/blitsort/src/blitsort.c
	# ../../thirdparty/owemdjee/blitsort/src/quadsort.c
	# ../../thirdparty/owemdjee/crumsort/src/crumsort.c
	# ../../thirdparty/owemdjee/crumsort/src/quadsort.c
	# ../../thirdparty/owemdjee/fluxsort/src/fluxsort.c
	# ../../thirdparty/owemdjee/fluxsort/src/quadsort.c
	# ../../thirdparty/owemdjee/fmath/tmp/catboost/contrib/libs/zstd/lib/dictBuilder/divsufsort.c
	# ../../thirdparty/owemdjee/fmath/tmp/catboost/contrib/libs/zstd06/dictBuilder/divsufsort.c
	# ../../thirdparty/owemdjee/fmath/tmp/catboost/contrib/python/numpy/py2/numpy/core/src/npysort/heapsort.c
	# ../../thirdparty/owemdjee/fmath/tmp/catboost/contrib/python/numpy/py2/numpy/core/src/npysort/mergesort.c
	# ../../thirdparty/owemdjee/fmath/tmp/catboost/contrib/python/numpy/py2/numpy/core/src/npysort/quicksort.c
	# ../../thirdparty/owemdjee/fmath/tmp/catboost/contrib/tools/yasm/libyasm/mergesort.c
	# ../../thirdparty/owemdjee/glib2/glib/gqsort.c
	# ../../thirdparty/owemdjee/gmt/src/compat/qsort.c
	# ../../thirdparty/owemdjee/gmt/src/mergesort.c
	# ../../thirdparty/owemdjee/gtsam/gtsam/3rdparty/metis/GKlib/sort.c
	# ../../thirdparty/owemdjee/gtsam/gtsam/3rdparty/metis/GKlib/test/gksort.c
	# ../../thirdparty/owemdjee/gtsam/gtsam/3rdparty/metis/libmetis/bucketsort.c
	# ../../thirdparty/owemdjee/harbour-core/contrib/gtnap/src/sewer/qsort.c
	# ../../thirdparty/owemdjee/harbour-core/src/vm/asort.c
	# ../../thirdparty/owemdjee/jpeg-xl/third_party/brotli/research/libdivsufsort/lib/divsufsort.c
	# ../../thirdparty/owemdjee/jpeg-xl/third_party/brotli/research/libdivsufsort/lib/sssort.c
	# ../../thirdparty/owemdjee/jpeg-xl/third_party/brotli/research/libdivsufsort/lib/trsort.c
	# ../../thirdparty/owemdjee/libdivsufsort/lib/divsufsort.c
	# ../../thirdparty/owemdjee/libdivsufsort/lib/sssort.c
	# ../../thirdparty/owemdjee/libdivsufsort/lib/trsort.c
	# ../../thirdparty/owemdjee/lzbench/zstd/lib/dictBuilder/divsufsort.c
	# ../../thirdparty/owemdjee/monolith/third-party/coin/ThirdParty/Mumps/MUMPS/PORD/lib/sort.c
	# ../../thirdparty/owemdjee/monolith/third-party/glpk/src/api/topsort.c
	# ../../thirdparty/owemdjee/mysql-connector-cpp/cdk/extra/zstd/lib/dictBuilder/divsufsort.c
	# ../../thirdparty/owemdjee/nfft/kernel/util/sort.c
	# ../../thirdparty/owemdjee/nsis/Source/bzip2/blocksort.c
	# ../../thirdparty/owemdjee/piposort/src/piposort.c
	# ../../thirdparty/owemdjee/quadsort/src/quadsort.c
	# ../../thirdparty/owemdjee/scilab/scilab/modules/elementary_functions/src/c/qsort.c
	# ../../thirdparty/owemdjee/sdcc/device/lib/pic14/libc/qsort.c
	# ../../thirdparty/owemdjee/sdcc/device/lib/qsort.c
	# ../../thirdparty/owemdjee/unicode-icu-demos/locexp/lxsort.c
	# ../../thirdparty/owemdjee/unicode-icu-demos/usort/lib/usort.c
	# ../../thirdparty/owemdjee/vcopy/src/gnu-src/sort.c
	# ../../thirdparty/owemdjee/vcopy/src/gnu-src/tsort.c
	# ../../thirdparty/owemdjee/vcopy/src/src/sort/radixsort.c
	# ../../thirdparty/owemdjee/vcopy/src/src/sort/sort.c
	# ../../thirdparty/owemdjee/vcopy/src/src/sort/vsort.c
	# ../../thirdparty/owemdjee/vcopy/src/src/tsort/tsort.c
	# ../../thirdparty/owemdjee/VQMT/tmp/DoG_SSIM___treammm/rf/RF_Class_C/src/qsort.c
	# ../../thirdparty/owemdjee/VQMT/tmp/DoG_SSIM___treammm/rf/RF_Reg_C/src/qsort.c
	# ../../thirdparty/owemdjee/vxl/v3p/bzlib/blocksort.c
	# ../../thirdparty/owemdjee/vxl/v3p/netlib/laso/dvsort.c
	# ../../thirdparty/owemdjee/wolfsort/src/blitsort.c
	# ../../thirdparty/owemdjee/wolfsort/src/crumsort.c
	# ../../thirdparty/owemdjee/wolfsort/src/fluxsort.c
	# ../../thirdparty/owemdjee/wolfsort/src/gridsort.c
	# ../../thirdparty/owemdjee/wolfsort/src/quadsort.c
	# ../../thirdparty/owemdjee/wolfsort/src/skipsort.c
	# ../../thirdparty/owemdjee/wolfsort/src/wolfsort.c
	# ../../thirdparty/owemdjee/zstd/lib/dictBuilder/divsufsort.c
	# ../../thirdparty/owemdjee/zsv/app/compare_sort.c
	# ../../tmp2/libplum___aaaaaa123456789/src/sort.c
	# ../../tmp2/libstego___zeratul2099/src/libstego/sort_unsort.c
	# ../../tmp2/Wimlib-Imagex-Package___chris1111/src/divsufsort.c
	# ../../tmp2/wimlib___ebiggers/src/divsufsort.c
		
	# ../../thirdparty/owemdjee/blitsort/src/bench.c
	# ../../thirdparty/owemdjee/catboost/contrib/python/numpy/py3/numpy/core/src/npysort/x86-simd-sort/benchmarks/bench-argsort.hpp
	# ../../thirdparty/owemdjee/catboost/contrib/python/numpy/py3/numpy/core/src/npysort/x86-simd-sort/benchmarks/bench-partial-qsort.hpp
	# ../../thirdparty/owemdjee/catboost/contrib/python/numpy/py3/numpy/core/src/npysort/x86-simd-sort/benchmarks/bench-qselect.hpp
	# ../../thirdparty/owemdjee/catboost/contrib/python/numpy/py3/numpy/core/src/npysort/x86-simd-sort/benchmarks/bench-qsort-common.h
	# ../../thirdparty/owemdjee/catboost/contrib/python/numpy/py3/numpy/core/src/npysort/x86-simd-sort/benchmarks/bench-qsort.cpp
	# ../../thirdparty/owemdjee/catboost/contrib/python/numpy/py3/numpy/core/src/npysort/x86-simd-sort/benchmarks/bench-qsort.hpp
	# ../../thirdparty/owemdjee/catboost/contrib/python/numpy/py3/numpy/core/src/npysort/x86-simd-sort/benchmarks/bench-qsortfp16.cpp
	# ../../thirdparty/owemdjee/crumsort/src/bench.c
	# ../../thirdparty/owemdjee/fluxsort/src/bench.c
	# ../../thirdparty/owemdjee/highway/hwy/contrib/sort/bench_parallel.cc
	# ../../thirdparty/owemdjee/highway/hwy/contrib/sort/bench_sort.cc
	# ../../thirdparty/owemdjee/piposort/src/bench.c
	# ../../thirdparty/owemdjee/quadsort/src/bench.c
	# ../../thirdparty/owemdjee/wolfsort/src/bench.c
