#! /bin/bash
# generated by generate_submodules_add_script.sh

pushd $(dirname $0)                                                                                     2> /dev/null   > /dev/null
cd ..


mode="R"

Win7DEV_BASEDIR=/media/sf_D_DRIVE/h/prj/1original/visyond/visyond

function git_submod_add {
    git submodule  add $1 $2
    if test "$mode" = "W" ; then
        git_register_remote_for_UnixVM $1 $2
    fi
}

function git_register_remote_for_UnixVM {
    if test -d "$2" ; then
        if test -d "$Win7DEV_BASEDIR/$2" ; then
            pushd $2                                                                                    2> /dev/null  > /dev/null
            git remote remove Win7DEV
            git remote add Win7DEV $Win7DEV_BASEDIR/$2
            popd                                                                                        2> /dev/null  > /dev/null
        fi
    fi
}

getopts ":Wh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
W )
  echo "--- registering Win7DEV as remote ---"
  mode="W"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  if test -d "$1" ; then
    Win7DEV_BASEDIR=$1
  fi
  #
  # register Win7DEV remote for main repo as well!
  if test -d "$Win7DEV_BASEDIR" ; then
    git remote remove Win7DEV
    git remote add Win7DEV $Win7DEV_BASEDIR
  fi
  ;;

"?" )
  echo "--- registering git submodules ---"
  mode="R"
  ;;

* )
  cat <<EOT
$0 [-W <optional_remote_path>]

set up git submodules / submodule references for all submodules.

-W       : set up 'Win7DEV' remote reference per submodule

           When you don't specify the remote path yourself,
           the default is set to:
             "$Win7DEV_BASEDIR"

EOT
  exit
  ;;
esac




git_submod_add   git@github.com:GerHobbelt/jpeginfo.git                                  thirdparty/jpeginfo
git_submod_add   git@github.com:GerHobbelt/langdata.git                                  thirdparty/tesseract_langdata
git_submod_add   git@github.com:GerHobbelt/langdata_lstm.git                             thirdparty/langdata_LSTM
git_submod_add   git@github.com:GerHobbelt/leptonica.git                                 thirdparty/leptonica
git_submod_add   git@github.com:GerHobbelt/libpng.git                                    thirdparty/libpng
git_submod_add   git@github.com:GerHobbelt/libtiff.git                                   thirdparty/libtiff
git_submod_add   git@github.com:GerHobbelt/tessconfigs.git                               thirdparty/tessconfigs
git_submod_add   git@github.com:GerHobbelt/tessdata.git                                  thirdparty/tessdata
git_submod_add   git@github.com:GerHobbelt/tessdata_best.git                             thirdparty/tessdata_best
git_submod_add   git@github.com:GerHobbelt/tessdata_contrib.git                          thirdparty/tessdata_contrib
git_submod_add   git@github.com:GerHobbelt/tessdata_fast.git                             thirdparty/tessdata_fast
git_submod_add   git@github.com:GerHobbelt/tessdoc.git                                   thirdparty/tessdoc
git_submod_add   git@github.com:GerHobbelt/tesseract.git                                 thirdparty/tesseract
git_submod_add   git@github.com:GerHobbelt/tesseract_docs.git                            thirdparty/tesseract_docs
git_submod_add   git@github.com:GerHobbelt/tesstrain.git                                 thirdparty/tesstrain
git_submod_add   git@github.com:GerHobbelt/thirdparty-curl.git                           thirdparty/curl
git_submod_add   git@github.com:GerHobbelt/thirdparty_extract.git                        thirdparty/extract



popd                                                                                                    2> /dev/null   > /dev/null

