
#include "../../thirdparty/owemdjee/gmime/tests/test-autocrypt.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-best.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-cat.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-encodings.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-filters.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-headers.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-html.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-iconv.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-mbox.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-mime-part.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-mime.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-parser.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-partial.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-pgp.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-pgpmime.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-pkcs7.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-smime.c"
#include "../../thirdparty/owemdjee/gmime/tests/test-streams.c"

#include "../../thirdparty/owemdjee/gmime/tests/testsuite.c"
