/* the compile-time options used to build the SQLite3 library
 *
 * https://github.com/azadkuh/sqlite-amalgamation
 */

#ifndef SQLITE3_CONFIG_H
#define SQLITE3_CONFIG_H

#define SQLITE_HAVE_ZLIB 
#define SQLITE_HAVE_C99_MATH_FUNCS 1
#undef SQLITE_HAVE_TCL

#ifndef SQLITE_ENABLE_DESERIALIZE
#define SQLITE_ENABLE_DESERIALIZE
#endif

#define SQLITE_ENABLE_DBSTAT_VTAB
#define SQLITE_ENABLE_FTS3
#define SQLITE_ENABLE_FTS4
#define SQLITE_ENABLE_FTS5
/* #undef SQLITE_ENABLE_GEOPOLY */
/* #undef SQLITE_ENABLE_ICU */
#define SQLITE_ENABLE_JSON1
#define SQLITE_ENABLE_MATH_FUNCTIONS
#define SQLITE_ENABLE_RBU
#define SQLITE_ENABLE_RTREE
/* #undef SQLITE_ENABLE_STAT4 */
/* #undef SQLITE_OMIT_DECLTYPE */
#define SQLITE_OMIT_LOAD_EXTENSION
#define SQLITE_OMIT_JSON
/* #undef SQLITE_USE_URI */
#define SQLITE_ENABLE_API_ARMOR
/* #undef SQLITE_ENABLE_EXPENSIVE_ASSERT */
#define SQLITE_ENABLE_FTS3_PARENTHESIS
#define SQLITE_ENABLE_SQLLOG
#define SQLITE_LOG_CACHE_SPILL
#define SQLITE_ENABLE_IOTRACE
#define SQLITE_ENABLE_SELECTTRACE
#define SQLITE_ENABLE_WHERETRACE
#define SQLITE_FORCE_OS_TRACE
#define SQLITE_USE_FCNTL_TRACE
#define SQLITE_LOCK_TRACE
#define SQLITE_PERFORMANCE_TRACE
#define SQLITE_ENABLE_OVERSIZE_CELL_CHECK
#define SQLITE_DEBUG 1
#define SQLITE_ENABLE_ATOMIC_WRITE
#define SQLITE_ENABLE_BATCH_ATOMIC_WRITE
#define SQLITE_ENABLE_COLUMN_METADATA
#define SQLITE_ENABLE_COLUMN_USED_MASK
#define SQLITE_ENABLE_COSTMULT
#define SQLITE_ENABLE_CURSOR_HINTS
/* #undef SQLITE_ENABLE_HIDDEN_COLUMNS */
#define SQLITE_ENABLE_STMT_SCANSTATUS
#ifndef SQLITE_ENABLE_PREUPDATE_HOOK
#define SQLITE_ENABLE_PREUPDATE_HOOK
#endif
#define SQLITE_ENABLE_UNLOCK_NOTIFY
#define SQLITE_ENABLE_MEMORY_MANAGEMENT
#define SQLITE_ENABLE_NORMALIZE
/* #undef SQLITE_ENABLE_NULL_TRIM */
#define SQLITE_ENABLE_EXPLAIN_COMMENTS
#define SQLITE_EXPLAIN_ESTIMATED_ROWS
#define SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION
/* #undef SQLITE_ENABLE_QPSG */
#define SQLITE_ENABLE_SESSION 1
#define SQLITE_ENABLE_SNAPSHOT
#define SQLITE_ENABLE_SORTER_REFERENCES
#define SQLITE_DEFAULT_AUTOMATIC_INDEX 0
#define SQLITE_DEFAULT_AUTOVACUUM 0
#define SQLITE_UNLINK_AFTER_CLOSE

#define SQLITE_RECOMMENDED_OPTIONS
#if defined(SQLITE_RECOMMENDED_OPTIONS)
#   define SQLITE_DQS 0
#   define SQLITE_DEFAULT_MEMSTATUS 0
#   define SQLITE_DEFAULT_WAL_SYNCHRONOUS 1
#   define SQLITE_LIKE_DOESNT_MATCH_BLOBS
#   define SQLITE_MAX_EXPR_DEPTH 50
//#   define SQLITE_OMIT_DECLTYPE
#   define SQLITE_OMIT_DEPRECATED
//#   define SQLITE_OMIT_PROGRESS_CALLBACK
#   define SQLITE_OMIT_SHARED_CACHE
#   define SQLITE_USE_ALLOCA
#endif /* SQLITE_RECOMMENDED_OPTIONS */

#if defined(SQLITE_OMIT_DECLTYPE) && defined(SQLITE_ENABLE_COLUMN_METADATA)
#  undef SQLITE_OMIT_DECLTYPE
#endif

#ifdef SQLITE_ENABLE_SQLLOG
void sqlite3_init_sqllog(void);
#endif

#endif /* SQLITE3_CONFIG_H */
